name: Release New Version

on:
  push:
    branches: ["master"]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Calculate Semver
        id: semver_rel
        uses: hennejg/github-tag-action@v4.3.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Changelog Builder
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fromTag: ${{ steps.semver_rel.outputs.previous_tag }}
          toTag: ${{ steps.semver_rel.outputs.new_tag }}
      - name: Create Github Release
        uses: mikepenz/action-gh-release@v0.2.0-a03
        with:
          body: ${{steps.github_release.outputs.changelog}}
          tag_name: ${{ steps.semver_rel.outputs.new_tag }}
  
  to_gitlab:
    runs-on: ubuntu-latest
    steps:                                             
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0                                          
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            git clone git@bitbucket.org:softpro-workworkwork/common-go.git
          ssh_private_key:                              
            ${{ secrets.BITBUCKET }}
